services: 
  oci_cron:
    build: .
    env_file: .env
    container_name: oci-sniper
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /home/ubuntu/.oci:/root/.oci:ro
      - /home/ubuntu/.ssh:/root/.ssh:ro

